### ISSUE TITLE
Support for Linux 5.4

### ISSUE THREAD

**Issue by pyriand3r** [sophos/talpa#18]
Hi,
I'm trying to compile talpa for my manjaro running the Kernel 5.4.2, but the `talpa-select select` command fails.

Logs says this:

```
Building...
Traceback (most recent call last):
  File "talpa_select.py", line 2035, in _action
  File "talpa_select.py", line 664, in select
  File "talpa_select.py", line 1555, in select
  File "talpa_select.py", line 1639, in build
  File "talpa_select.py", line 1792, in __try_build
SelectException: exc-build-failed
```

Any idea?

**Comment by paperclip** [comment]
I'm afraid the current version of Talpa on github doesn't support kernel 5.4 (or 5.2 or 5.3).

We are working on releasing a fixed version of Talpa. In the mean-time you could try using fanotify.

**Comment by paperclip** [comment]
We have released updates to Talpa (both master and perforce branches) that should allow Talpa to compile on kernel 5.4.
Also fixes various initialised memory issues.
