### ISSUE TITLE
can't compile Debian 4.14.12-2 (2018-01-06) x86_64

### ISSUE THREAD

**Issue by grandtoubab** [sophos/talpa#8]
hello
After build using autodeploy.sh

```
root@debian:/opt/av-sophos/talpa/override# ls -alrt
total 452
-rw-r--r-- 1 root root     35 janv.  7 14:27 build.options
-rw-r--r-- 1 root root 447593 janv.  7 14:30 talpa-srcpack.tar.gz
drwx------ 2 root root   4096 janv.  7 14:30 .
drwx------ 7 root root   4096 janv.  7 14:35 ..
```
Talpa_select failed

```
root@debian:/opt/av-sophos/engine# ./talpa_select select
[Talpa-select]
Copyright 1989-2017 Sophos Limited. All rights reserved.
Sun Jan  7 13:35:06 2018 GMT
Linux distribution: [debian]
Product: [Debian GNU/Linux stable-updates (sid)]
Kernel: [4.14.0-3-amd64]
Multiprocessor support enabled.
Searching for source pack...
Searching for suitable binary pack...
No suitable binary pack available.
Preparing for build...
Extracting sources...
Configuring build of version 0.9.95...
Building...
Error: Failed to build from source.
root@debian:/opt/av-sophos/engine
```

```
root@debian:/opt/av-sophos/log# tail -f talpaselect.log
config.status: executing depfiles commands

Building...
Traceback (most recent call last):
  File "talpa_select.py", line 2216, in _action
  File "talpa_select.py", line 845, in select
  File "talpa_select.py", line 1736, in select
  File "talpa_select.py", line 1820, in build
  File "talpa_select.py", line 1973, in __try_build
SelectException: exc-build-failed
```

**Comment by paperclip** [comment]
There should be a build.log IIRC, somewhere under /opt/sophos-av/talpa/ 
That should tell us what failed.

**Comment by grandtoubab** [comment]
Dont find any build.log
```
root@debian:/opt/av-sophos/talpaa-kernel-414# ls 
aclocal.m4	clients      config.status  include	    Makefile26.in  manifest.spec  src			tests
AUTHORS		config	     configure	    INSTALL	    makefile.am    NEWS		  stamp-h1		TODO
autom4te.cache	config.h     configure.ac   interface.spec  Makefile.am    README	  support
bootstrap	config.h.in  COPYING	    LICENSE	    makefile.in    README.md	  talpa-0.9.95
ChangeLog	config.log   doc	    makefile	    manifest.sig   source.spec	  talpa-srcpack.tar.gz
```

only that one
[config.log](https://github.com/sophos/talpa/files/1611476/config.log)

NB it is successfull with those

```
root@debian:/opt/av-sophos/talpa/compiled# ls
talpa-binpack-debian-x86_64-4.14.0-1-amd64-1smpdebian4142120171130.tar.gz
talpa-binpack-debian-x86_64-4.14.0-2-amd64-1smpdebian4147120171222.tar.gz
talpa-binpack-debian-x86_64-4.9.0-4-amd64-1smpdebian4951120170928.tar.gz
talpa-binpack-debian-x86_64-4.9.0-4-amd64-1smpdebian49653deb9u120171223.tar.gz
talpa-binpack-debian-x86_64-4.9.0-5-amd64-1smpdebian49653deb9u220180104.tar.gz
```

**Comment by paperclip** [comment]
Hi,
We tried building Talpa, using our copy of the code, and it worked fine.
The uname -a of the kernel is: Linux debian9-heloise 4.14.0-3-amd64 #1 SMP Debian 4.14.12-2 (2018-01-06) x86_64 GNU/Linux

If the build fails it should record the information to:
/opt/av-sophos/talpa/build/talpa-*/build.log
(where * is the talpa version.)

Please check the source is up to date (re-run autodeploy.sh)

**Comment by grandtoubab** [comment]
Hello
Same error
```
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/opt/av-sophos/talpa-kernel-414':
configure: error: C compiler cannot create executables
See `config.log' for more details
Unable to configure

```
Here is the log file

[config.log](https://github.com/sophos/talpa/files/1680822/config.log)

**Comment by paperclip** [comment]
The config.log has:

/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory

I think that means something that gcc needs to compile has been uninstalled.

**Comment by paperclip** [comment]
Make sure libc6-dev package is installed.

**Comment by grandtoubab** [comment]
You are right.
after adding
```
 apt list libc6-dev
En train de lister... Fait
libc6-dev/testing,now 2.26-4 amd64  [installé]
```
Sophos starts well
```
● sav-protect.service - "Sophos Anti-Virus daemon"
   Loaded: loaded (/lib/systemd/system/sav-protect.service; enabled; vendor preset: enabled)
   Active: activating (start-pre) since Thu 2018-02-01 11:11:06 CET; 2min 20s ago
     Docs: man:sav-protect
Cntrl PID: 4250 (.sav-protect.sy)
    Tasks: 14 (limit: 4915)
   CGroup: /system.slice/sav-protect.service
           ├─4250 /bin/sh /opt/av-sophos/engine/.sav-protect.systemd.prestart.sh
           ├─4857 /opt/av-sophos/engine/python /opt/av-sophos/engine/_/talpa_select select
           ├─5830 /usr/bin/make TALPA_ID='-DTALPA_ID="b2f6a75a19c5ba26fc0f3bd4cc4a36c6"' TALPA_SYSCALL_TABLE='-DTALPA_SYSCALL_TABLE=0xf
           ├─5835 /usr/bin/make all-recursive
           ├─5838 /bin/bash -c fail=; \ if (target_option=k; case ${target_option-} in ?) ;; *) echo "am__make_running_with_option: int
           ├─5853 /usr/bin/make all-am
           ├─5856 /usr/bin/make -C /lib/modules/4.14.0-3-amd64/build M=/opt/av-sophos/talpa/build/talpa-0.9.95 modules
           ├─5857 /usr/bin/make -C /usr/src/linux-headers-4.14.0-3-common O=/usr/src/linux-headers-4.14.0-3-amd64 modules
           ├─5861 /usr/bin/make -C /usr/src/linux-headers-4.14.0-3-amd64 KBUILD_SRC=/usr/src/linux-headers-4.14.0-3-common -f /usr/src/
           ├─6228 /usr/bin/make -f /usr/src/linux-headers-4.14.0-3-common/scripts/Makefile.build obj=/opt/av-sophos/talpa/build/talpa-0
           ├─7090 /bin/sh -c set -e;     echo '  CC [M]  /opt/av-sophos/talpa/build/talpa-0.9.95/src/app-ctrl/filter-iface/vetting-clie
           ├─7091 gcc-7 -Wp,-MD,/opt/av-sophos/talpa/build/talpa-0.9.95/src/app-ctrl/filter-iface/vetting-clients/talpa-vcdevice/.talpa
           ├─7092 /usr/lib/gcc/x86_64-linux-gnu/7/cc1 -quiet -nostdinc -I /usr/src/linux-headers-4.14.0-3-common/arch/x86/include -I ./
           └─7093 as -I /usr/src/linux-headers-4.14.0-3-common/arch/x86/include -I ./arch/x86/include/generated -I /usr/src/linux-heade

févr. 01 11:11:06 debian systemd[1]: Starting "Sophos Anti-Virus daemon"...
```
And finally
```
root@debian:/# systemctl status sav-protect.service -l
● sav-protect.service - "Sophos Anti-Virus daemon"
   Loaded: loaded (/lib/systemd/system/sav-protect.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-02-01 11:13:59 CET; 5min ago
     Docs: man:sav-protect
  Process: 7601 ExecStartPost=/opt/av-sophos/engine/.sav-protect.systemd.poststart.sh (code=exited, status=0/SUCCESS)
  Process: 4250 ExecStartPre=/opt/av-sophos/engine/.sav-protect.systemd.prestart.sh (code=exited, status=0/SUCCESS)
 Main PID: 7600 (savd)
    Tasks: 34 (limit: 4915)
   CGroup: /system.slice/sav-protect.service
           ├─7600 savd etc/savd.cfg
           ├─7663 savscand --incident=unix://tmp/incident --namedscan=unix://root@tmp/namedscansprocessor.0 --ondemandcontrol=socketpair://38/39 
           └─7707 savscand --incident=unix://tmp/incident socketpair://45/46 --threads=5

févr. 01 11:11:06 debian systemd[1]: Starting "Sophos Anti-Virus daemon"...
févr. 01 11:11:16 debian .sav-protect.systemd.prestart.sh[4250]: No TBP available, running savupdate:
févr. 01 11:13:44 debian savd[7600]: savd.daemon: SAVD-STARTED
févr. 01 11:13:56 debian savd[7600]: savd.daemon: ONACCESS-ENABLED talpa
févr. 01 11:13:59 debian systemd[1]: Started "Sophos Anti-Virus daemon".
```
```
root@debian:/opt/av-sophos/talpa/compiled# ls -alrt
total 396
-rw------- 1 root sophosav  90498 oct.  20 11:39 talpa-binpack-debian-x86_64-4.9.0-4-amd64-1smpdebian4951120170928.tar.gz
-rw------- 1 root sophosav  90454 déc.  24 12:05 talpa-binpack-debian-x86_64-4.9.0-4-amd64-1smpdebian49653deb9u120171223.tar.gz
-rw------- 1 root root      90462 janv.  7 20:04 talpa-binpack-debian-x86_64-4.9.0-5-amd64-1smpdebian49653deb9u220180104.tar.gz
-rw------- 1 root root     111649 févr.  1 11:13 talpa-binpack-debian-x86_64-4.14.0-3-amd64-1smpdebian41413120180114.tar.gz
drwx------ 6 root sophosav   4096 févr.  1 11:13 ..
drwx------ 2 root sophosav   4096 févr.  1 11:26 .
root@debian:/opt/av-sophos/talpa/compiled# 

```
```
root@debian:/opt/av-sophos/bin# ./savdstatus
Sophos Anti-Virus is active and on-access scanning is running
root@debian:/opt/av-sophos/bin# 
```
